name: eco_bloom_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7
  provider: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/compost_bin.jpg
    - assets/images/watering_can.jpg
    - assets/images/bamboo_trowel.jpg
    - assets/images/rain_barrel.jpg
    - assets/images/herb_seeds.jpg
    - assets/images/drip_kit.jpg
    - assets/images/grow_bags.jpg
    - assets/images/hemp_gloves.jpg
    - assets/images/neem_spray.jpg
    - assets/images/worm_kit.jpg
    - assets/images/seed_tray.jpg
    - assets/screenshots/ecobloom_hmpg.png
    - assets/screenshots/ecobloom_cart.png
